# Generated by Django 5.0.1 on 2024-01-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_employee_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
    ]
